version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)

  build:
    commands:
      - "./gradlew assemble"
      - "docker build -t watchtower-service:latest watchtower-service/"
      - "docker tag watchtower-service:latest 195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower/watchtower-service:latest"

  post_build:
    commands:
      - "docker push 195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower/watchtower-service:latest"

cache:
  paths:
    - '/root/.m2/**/*'