version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - "./gradlew assemble"

artifacts:
  files:
    - watchtower-service/build/libs/watchtower-service-0.1.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'