version: "3"
services:

  mysql:
    image: mysql:8
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: watchtower
      MYSQL_PASSWORD: watchtower
      MYSQL_DATABASE: watchtower
    healthcheck:
#      test: mysqladmin ping -h 127.0.0.1 -u watchtower --password=watchtower
      test: ["CMD", 'wait-for-it mysql:3306']
      interval: 10s
      timeout: 2s
      retries: 10

  backend:
    build: ./watchtower-service
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    volumes:
      - $PWD:/work
    working_dir: /work

  frontend:
    build: ./watchtower-gui
    networks:
      - frontend
    ports:
      - 8000:80

networks:
  frontend: {}
  backend: {}
