version: "3"
services:

  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - 27017:27017

  backend:
    build: ./watchtower-service
#    image: watchtower-service:latest
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - $PWD:/work
    working_dir: /work

  frontend:
    build: ./watchtower-gui
#    image: watchtower-gui:latest
    networks:
      - frontend
    ports:
      - 8000:80

networks:
  frontend: {}
  backend: {}
