version: "3"
services:

  db:
    image: mysql:8
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: watchtower
      MYSQL_PASSWORD: watchtower
      MYSQL_DATABASE: watchtower

  backend:
    build:
      context: ./watchtower-service
      dockerfile: Dockerfile-livedev
    image: tower-backend:livedev
    command: bash -c 'wait-for-it.sh db:3306 -t 60; ./gradlew watchtower-service:run --continuous'
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MICRONAUT_ENVIRONMENTS: livedev
      MICRONAUT_CONFIG_FILES: $PWD/tower.yml
      TOWER_LOG_DIR: $PWD
    volumes:
      - $HOME/.me:/root/.me
      - $HOME/.gradle:/root/.gradle
      - $PWD:$PWD
    working_dir: $PWD
    depends_on:
      - db

  frontend:
    build:
      context: ./watchtower-gui
      dockerfile: Dockerfile-livedev
    image: tower-frontend:livedev
    command: bash -c 'npm i; ng serve --live-reload --watch --poll 3000 --host 0.0.0.0 --port 4200 --proxy-config proxy.conf.json -c livedev'
    volumes:
      - $PWD/watchtower-gui:$PWD/watchtower-gui
    working_dir: $PWD/watchtower-gui
    networks:
      - frontend
    ports:
      - 4200:4200
    depends_on:
      - backend

networks:
  frontend: {}
  backend: {}
