version: "3"
services:

  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - 27017:27017

  backend:
    build: ./watchtower-service
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MICRONAUT_ENVIRONMENTS: livedev
    volumes:
      - $PWD:/work
    working_dir: /work

  frontend:
    build:
      context: ./watchtower-gui
      dockerfile: Dockerfile-livedev
    image: ng-tower:livedev
    command: bash -c 'npm i; ng serve --watch --host 0.0.0.0 --port 4200 --proxy-config proxy.conf.json -c livedev'
    volumes:
      - $PWD/watchtower-gui:$PWD/watchtower-gui
    working_dir: $PWD/watchtower-gui
    networks:
      - frontend
    ports:
      - 4200:4200

networks:
  frontend: {}
  backend: {}
