version: "3"
services:

  db:
    image: mysql:5.7
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: tower
      MYSQL_PASSWORD: tower
      MYSQL_DATABASE: tower

  backend:
    build: ./watchtower-service
    command: bash -c 'wait-for-it.sh db:3306 -t 60; backend-up.sh'
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - $PWD:/work
    working_dir: /work
    depends_on:
      - db

  frontend:
    build: ./watchtower-gui
    networks:
      - frontend
    ports:
      - 8000:80
    depends_on:
      - backend

networks:
  frontend: {}
  backend: {}
