version: "3.3"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: watchtower
      MYSQL_PASSWORD: watchtower
      MYSQL_DATABASE: watchtower