version: "3.3"

services:
  mongo:
    image: mongo:4.1
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: watchtower
      ME_CONFIG_MONGODB_ADMINPASSWORD: watchtower