---
micronaut:
  application:
    name: watchtower-service
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/watchtower"

grails:
  mongodb:
    databaseName: watchtower
---