---
micronaut:
  application:
    name: watchtower-service
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/watchtower"

grails:
  mongodb:
    databaseName: watchtower
---
mail:
  from: info@seqera.io
  smtp:
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587
    auth: true
    starttls:
      enable: true
      required: true
