---
micronaut:
  application:
    name: watchtower-service
  server:
    netty:
      child-options:
        SO_TIMEOUT: 420000
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
        generator:
          access-token-expiration: 3600
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
dataSource:
  pooled: true
  dbCreate: update
  url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/watchtower"
  driverClassName: com.mysql.cj.jdbc.Driver
  username: watchtower
  password: watchtower
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: org.hibernate.dialect.MySQL8Dialect
grails:
  gorm:
    failOnError: false
---
mail:
  from: info@seqera.io
  to: qa@salenda.es
  smtp:
    host: smtp.salenda.es
    port: 25
    auth: false
    starttls:
      enable: false
      required: false
---
front:
  url: http://localhost:8000
---
sse:
  time:
    idle:
      workflow-detail: 5m
      workflow-list: 3600s
    throttle:
      workflow-detail: 1s
      workflow-list: 0s


