---
micronaut:
  application:
    name: watchtower-service
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
#mongodb:
#  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/watchtower"
#
#grails:
#  mongodb:
#    databaseName: watchtower
dataSource:
  pooled: true
  dbCreate: update
  url: jdbc:postgresql://localhost:5432/watchtower
  driverClassName: org.postgresql.Driver
  username: watchtower
  password: watchtower
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: org.hibernate.dialect.PostgreSQLDialect
grails:
  gorm:
    failOnError: false
---
mail:
  from: info@seqera.io
  smtp:
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587
    auth: true
    starttls:
      enable: true
      required: true
---
front:
  url: http://localhost:8000
---
