---
dataSource:
  pooled: true
  dbCreate: create-drop
  url: jdbc:mysql://localhost:3307/watchtower
  driverClassName: com.mysql.jdbc.Driver
  username: watchtower
  password: watchtower
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: org.hibernate.dialect.MySQL8Dialect
grails:
  gorm:
    failOnError: false
---
mail:
  debug: true
  from: me@google.com
  smtp:
    host: localhost
    port: 3025
    user: mr-bean
    password: super-secret
    auth: true
    starttls:
      enable: false
      required: false
    proxy:
      host: proxy.com
      port: 5566
---
front:
  url: http://localhost:4200
---
auth:
  mail:
    duration: 30m
---
sse:
  idle:
    timeout: 5s
