---
micronaut:
  application:
    name: watchtower-service
  server:
    netty:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
        generator:
          access-token-expiration: 3600
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  serialization-inclusion: ALWAYS
# ^^^^^^
# Use this to avoid empty lists are stripped
# See com.fasterxml.jackson.annotation.JsonInclude.Include.*
#
dataSource:
  pooled: true
  dbCreate: update
  url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/tower"
  driverClassName: com.mysql.cj.jdbc.Driver
  username: tower
  password: tower
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: org.hibernate.dialect.MySQL57Dialect
grails:
  gorm:
    failOnError: false
---
mail:
  from: info@seqera.io
  smtp:
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587
    auth: true
    starttls:
      enable: true
      required: true
---
front:
  url: http://localhost:8000
---
sse:
  time:
    idle:
      workflow-detail: 5m
      workflow-list: 3600s
    throttle:
      workflow-detail: 1s
      workflow-list: 0s
    heartbeat:
      workflow-list: 1m

