---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27018}/watchtower"

grails:
  mongodb:
    databaseName: watchtower

---
mail:
  debug: true
  from: me@google.com
  smtp:
    host: google.com
    port: 587
    user: mr-bean
    password: super-secret
    auth: true
    starttls:
      enable: true
      required: true
    proxy:
      host: proxy.com
      port: 5566
---
#dataSource:
#  pooled: true
#  dbCreate: update
#  url: jdbc:postgresql://localhost:5432/watchtower
#  driverClassName: org.postgresql.Driver
#  username: watchtower
#  password: watchtower
#
#hibernate:
#  cache:
#    queries: false
#    use_second_level_cache: false
#    use_query_cache: false
#  dialect: org.hibernate.dialect.PostgreSQLDialect
#
#grails:
#  gorm:
#    failOnError: false