#
# configuration used for dockerized dev environment
#
micronaut:
  server:
    cors:
      enabled: true
  io:
    watch:
      paths: src/main
      restart: true
---
mail:
  from: info@seqera.io
  smtp:
    host: smtp.salenda.es
    port: 25
    auth: false
    starttls:
      enable: false
      required: false

---
mail:
  from: info@seqera.io
  smtp:
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587
    auth: true
    starttls:
      enable: true
      required: true
