---
dataSource:
  pooled: false
  dbCreate: create-drop
  url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ""
hibernate:
  show_sql: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: org.hibernate.dialect.H2Dialect
grails:
  gorm:
    failOnError: false
---
mail:
  debug: true
  from: me@google.com
  smtp:
    host: localhost
    port: 3025
    user: mr-bean
    password: super-secret
    auth: true
    starttls:
      enable: false
      required: false
    proxy:
      host: proxy.com
      port: 5566
---
auth:
  mail:
    duration: 30m
---
sse:
  time:
    idle:
      workflow-detail: 1m
      workflow-list: 1m
    throttle:
      workflow-detail: 0s
      workflow-list: 0s
    heartbeat:
      workflow-list: 1m
